### ISSUE TITLE
Error on startup - java.lang.NoClassDefFoundError: com/intellij/psi/PsiClass

### ISSUE THREAD

**Issue by Copystrike** [KikiManjaro/StickyScroll#15]
Hey, when starting the StickyScroll plugin version 0.0.2 in Webstorm, an error occurs and prevents the plugin from loading properly. The error message suggests a `NoClassDefFoundError` for the class `com.intellij.psi.PsiClass`. This error prevents the plugin from functioning correctly.

**Error Message:**
```
java.lang.NoClassDefFoundError: com/intellij/psi/PsiClass
	at com.github.kikimanjaro.stickyscroll.marshaller.DefaultParentMarshaller$getParents$1$1.invoke(DefaultParentMarshaller.kt:11)
	at com.github.kikimanjaro.stickyscroll.marshaller.DefaultParentMarshaller$getParents$1$1.invoke(DefaultParentMarshaller.kt:11)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at com.github.kikimanjaro.stickyscroll.listeners.ScrollListener.visibleAreaChanged(ScrollListener.kt:42)
	at com.intellij.openapi.editor.impl.ScrollingModelImpl$MyChangeListener.stateChanged(ScrollingModelImpl.java:550)
	at java.desktop/javax.swing.JViewport.fireStateChanged(JViewport.java:1494)
	at java.desktop/javax.swing.JViewport$ViewListener.componentResized(JViewport.java:1413)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6482)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.fireResized(EditorComponentImpl.java:215)
	at com.intellij.openapi.editor.impl.EditorImpl.validateSize(EditorImpl.java:1816)
	at com.intellij.openapi.editor.impl.EditorImpl.recalculateSizeAndRepaint(EditorImpl.java:1825)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.notifyBatchFoldingProcessingDone(FoldingModelImpl.java:488)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:297)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:232)
	at com.intellij.openapi.editor.FoldingModel.runBatchFoldingOperationDoNotCollapseCaret(FoldingModel.java:107)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.lambda$buildInitialFoldings$1(CodeFoldingManagerImpl.java:145)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.lambda$loadEditorInBackground$5(PsiAwareTextEditorImpl.java:78)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.loadingFinished(AsyncEditorLoader.kt:166)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.access$loadingFinished(AsyncEditorLoader.kt:24)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$start$2$1.invokeSuspend(AsyncEditorLoader.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiClass PluginClassLoader(plugin=PluginDescriptor(name=StickyScroll, id=com.github.kikimanjaro.stickyscroll, descriptorPath=plugin.xml, path=D:\programs\jetbrains\toolbox\apps\WebStorm\ch-0\231.8770.64.plugins\StickyScroll-0.0.2.jar, version=0.0.2, package=null, isBundled=false), packagePrefix=null, instanceId=66, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 61 more

```

**Steps to Reproduce:**

- Launch Webstorm.
- Install the StickyScroll plugin version 0.0.2.
- Restart Webstorm.
- Observe the error message.

**Expected Behavior:**

The StickyScroll plugin should load successfully without any errors, allowing users to access its features.

**Additional Information:**

Operating System: Windows
WebStorm Version: 2023.1.1
StickyScroll Plugin Version: 0.0.2

**Comment by HoldYourWaffle** [comment]
This error (and similar) appears for me when building the project, but strangely not when installing from the marketplace in IntelliJ 2023.1.2...
Could there be a misconfigured dependency somewhere?
